/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 my_street.gltf --transform
Author: kluchek (https://sketchfab.com/kluchek)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/street-38254a2cf59a4df4aa8b0a352f807749
Title: Street
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model() {
  const { nodes, materials } = useGLTF('/street-transformed.glb')
  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.palette} position={[-50, -48.5, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/my_street-transformed.glb')
